#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application();

$app->add(new \Wilf\Console\Command\GreetCommand()); // php run console:greet
$app->add(new \Wilf\Console\Command\InputCommand()); // php run console:input

$app->run();
