#!/usr/bin/env php
<?php
/*
 * Copyright (c) 2022. Tom Wilford <hello@jollyblueman.com>
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application();

$app->add(new \Wilf\Console\Command\GreetCommand()); // php run console:greet
$app->add(new \Wilf\Console\Command\InputCommand()); // php run console:input

$app->run();
