# config/services.yml
services:
  _defaults:
    autowire: true

  App\:
    resource: '/../src/Console/'

  Symfony\Component\Console\Application:
    # why public? so we can get it from container in bin file
    # via "$container->get(Application::class)"
    public: true